"""Add information tables

Revision ID: 04bee121dc03
Revises: 6e567049a850
Create Date: 2026-07-24 17:53:13.033222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bee121dc03'
down_revision = '6e567049a850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information_months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_information_month')
    )
    op.create_table('information_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('group_no', sa.Integer(), nullable=False),
    sa.Column('gauge_serial', sa.String(length=100), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('days', sa.Float(), nullable=True),
    sa.Column('well_number', sa.String(length=100), nullable=True),
    sa.Column('changed_to', sa.String(length=100), nullable=True),
    sa.Column('survey', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('rig_name', sa.String(length=100), nullable=True),
    sa.Column('bundle_carrier_sn', sa.String(length=100), nullable=True),
    sa.Column('battery_sn', sa.String(length=100), nullable=True),
    sa.Column('engineer', sa.String(length=100), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('attachment_original_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information_rows')
    op.drop_table('information_months')
    # ### end Alembic commands ###
