"""Remove language setting

Revision ID: 14a928c9261e
Revises: 8e59918e2360
Create Date: 2026-07-31 23:49:47.170455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a928c9261e'
down_revision = '8e59918e2360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
