"""Add pressure test date to bundle carriers

Revision ID: 5cda4e77b8f6
Revises: a383751f7046
Create Date: 2026-07-28 11:34:18.521607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cda4e77b8f6'
down_revision = 'a383751f7046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle_carriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pressure_test_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle_carriers', schema=None) as batch_op:
        batch_op.drop_column('pressure_test_date')

    # ### end Alembic commands ###
