"""Create app settings table

Revision ID: 8e59918e2360
Revises: f108c1017e0b
Create Date: 2026-07-31 23:22:04.963899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e59918e2360'
down_revision = 'f108c1017e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('company_logo', sa.String(length=255), nullable=True),
    sa.Column('company_email', sa.String(length=120), nullable=True),
    sa.Column('company_phone', sa.String(length=50), nullable=True),
    sa.Column('company_address', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('date_format', sa.String(length=30), nullable=True),
    sa.Column('time_format', sa.String(length=20), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
