"""Add previous consumption to batteries

Revision ID: a383751f7046
Revises: c84f3b9e1a20
Create Date: 2026-07-28 00:09:08.155181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a383751f7046'
down_revision = 'c84f3b9e1a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.add_column(
        sa.Column(
            'previous_consumption',
            sa.Float(),
            nullable=False,
            server_default='0'
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.drop_column('previous_consumption')

    # ### end Alembic commands ###
