"""Add position to information

Revision ID: e6282da4f611
Revises: 5cda4e77b8f6
Create Date: 2026-07-28 12:02:37.180891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6282da4f611'
down_revision = '5cda4e77b8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information_rows', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
